version: '3'
services:
  app:
    image: hitalos/laravel
    depends_on:
      - database
    volumes:
      - .:/var/www
    ports:
      - 80:80

  # queue:
  #   image: hitalos/laravel
  #   command: php artisan queue:work --timeout 90 --tries 3
  #   depends_on:
  #     - app
  #     - redis
  #   volumes:
  #     - .:/var/www
  #   ports:
  #     - 80:80

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=someSecretPassword"
      - "MYSQL_DATABASE=justificaciones"

  # redis:
  #   image: redis:3.2-alpine
  #   ports:
  #     - 6379:6379